package de.kontext_e.golaas.jni;

/*Generated by MPS */

import javax.annotation.Generated;
import org.apache.log4j.Logger;

@Generated(value = "MPS JNI Java Generator")
public final class CallbackRegistry {
  private static final Logger LOGGER = Logger.getLogger(CallbackRegistry.class);

  public static void registerCallbacks() {
    registerAndLog(JniInterface.registerOpenCB(new OpenCallback()), "Open");
    registerAndLog(JniInterface.registerCloseCB(new CloseCallback()), "Close");
    registerAndLog(JniInterface.registerGetVersionCB(new GetVersionCallback()), "GetVersion");
    registerAndLog(JniInterface.registerSetStartGenerationCB(new SetStartGenerationCallback()), "SetStartGeneration");
    registerAndLog(JniInterface.registerCalculateGenerationsCB(new CalculateGenerationsCallback()), "CalculateGenerations");
  }

  private static void registerAndLog(long status, String commandName) {
    if (0 != status) {
      LOGGER.error(String.format("Could not register %s ".concat(String.valueOf(status)), commandName));
    } else {
      LOGGER.debug(String.format("Registered %s ".concat(String.valueOf(status)), commandName));
    }
  }

  private CallbackRegistry() {
  }
}
