package de.kontext_e.golaas.jni;

/*Generated by MPS */

import javax.annotation.Generated;
import de.kontext_e.golaas.model.ReplyDto;
import java.util.Arrays;

@Generated(value = "MPS JNI Java Generator")
public class GetVersionReplyDto implements ReplyDto {
  private byte returnCode;
  private byte[] version;

  public GetVersionReplyDto(byte returnCode, byte[] version) {
    this.returnCode = returnCode;
    this.version = version;
  }

  public byte getReturnCode() {
    return returnCode;
  }
  public byte[] getVersion() {
    return version;
  }


  @Override
  public String toString() {
    StringBuilder stringBuilder = new StringBuilder();
    stringBuilder.append("GetVersionDto");
    stringBuilder.append("{ ");
    stringBuilder.append("returnCode=" + returnCode + ", ");
    stringBuilder.append("version=" + version + ", ");
    stringBuilder.append("}");
    return stringBuilder.toString();
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;

    result = 31 * result + (int) returnCode;
    result = 31 * result + Arrays.hashCode(version);
    return result;
  }


  @Override
  public boolean equals(Object object) {
    if (this == object) {
      return true;
    }
    if (object == null) {
      return false;
    }
    if (getClass() != object.getClass()) {
      return false;
    }

    GetVersionReplyDto other = (GetVersionReplyDto) object;
    if (returnCode != other.returnCode) {
      return false;
    }
    if (!(Arrays.equals(version, other.version))) {
      return false;
    }

    return true;
  }
}
