package de.kontext_e.golaas.jni;

/*Generated by MPS */

import javax.annotation.Generated;

@Generated(value = "MPS JNI Java Generator")
public abstract class JniInterface {
  public static native long initialize();

  public static native long registerOpenCB(OpenCallback callback);
  public static native long registerCloseCB(CloseCallback callback);
  public static native long registerGetVersionCB(GetVersionCallback callback);
  public static native long registerSetStartGenerationCB(SetStartGenerationCallback callback);
  public static native long registerCalculateGenerationsCB(CalculateGenerationsCallback callback);

  public static native long Open();
  public static native long Close();
  public static native long GetVersion();
  public static native long SetStartGeneration(byte width, byte height, byte[] livingX, byte[] livingY);
  public static native long CalculateGenerations(byte numberOfGenerations);
}
