package de.kontext_e.golaas.jni;

/*Generated by MPS */

import javax.annotation.Generated;
import de.kontext_e.golaas.model.ReplyDto;

@Generated(value = "MPS JNI Java Generator")
public class OpenReplyDto implements ReplyDto {
  private byte returnCode;

  public OpenReplyDto(byte returnCode) {
    this.returnCode = returnCode;
  }

  public byte getReturnCode() {
    return returnCode;
  }


  @Override
  public String toString() {
    StringBuilder stringBuilder = new StringBuilder();
    stringBuilder.append("OpenDto");
    stringBuilder.append("{ ");
    stringBuilder.append("returnCode=" + returnCode + ", ");
    stringBuilder.append("}");
    return stringBuilder.toString();
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;

    result = 31 * result + (int) returnCode;
    return result;
  }


  @Override
  public boolean equals(Object object) {
    if (this == object) {
      return true;
    }
    if (object == null) {
      return false;
    }
    if (getClass() != object.getClass()) {
      return false;
    }

    OpenReplyDto other = (OpenReplyDto) object;
    if (returnCode != other.returnCode) {
      return false;
    }

    return true;
  }
}
